version: '3'
services:
  backend:
    image: node-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    environment:
      - PORT=5000
    depends_on:
      - frontend
  frontend:
    image: react-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend